---
- name: web1
  group: "[webservers]"
  box: oravirt/ol65
  ram: 512
  ip: 192.168.9.91
  private_key: /home/miksan/.vagrant.d/insecure_private_key

- name: web2
  group: "[webservers]"
  box: oravirt/ol65
  ram: 512
  ip: 192.168.9.92
  private_key: /home/miksan/.vagrant.d/insecure_private_key

- name: web3
  group: "[webservers]"
  box: oravirt/ol65
  ram: 512
  ip: 192.168.9.93
  private_key: /home/miksan/.vagrant.d/insecure_private_key

#- name: web4
#  group: "[webservers]"
#  box: oravirt/ol65
#  ram: 512
#  ip: 192.168.9.94
#  private_key: /home/miksan/.vagrant.d/insecure_private_key

#- name: web5
#  group: "[webservers]"
#  box: oravirt/ol65
#  ram: 512
#  ip: 192.168.9.95
#  private_key: /home/miksan/.vagrant.d/insecure_private_key

- name: lb
  group: "[loadbalancer]"
  box: oravirt/ol65
  ram: 1024
  ip: 192.168.9.90
  private_key: /home/miksan/.vagrant.d/insecure_private_key
