---
  - name: Install EPEL Repo
    yum: name={{ epel_rpm }} state=installed

  - name: Start and enable NTP
    service: name=ntpd  state=started  enabled=yes

  - name: Install nginx
    yum: name=nginx state=installed
    
  - name: Start & Enable nginx
    service: name=nginx state=started enabled=yes

  - name: Add default page
    template: src=index.html.j2 dest=/usr/share/nginx/html/index.html
    when: inventory_hostname != 'lb'
    notify: Restart nginx

  - name: Add nginx lb config
    template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
    when: inventory_hostname == 'lb'
    notify: Restart nginx
    tags: lb
